# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: windows-2019

variables:
  buildConfiguration: 'Release'
  Parameters.RestoreBuildProjects: '**/*.csproj'
  Parameters.TestProjects: '**/*Tests/*.csproj'

steps:

- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: '$(Parameters.RestoreBuildProjects)'
- task: SonarCloudPrepare@1
  displayName: Sonar Cloud Prepare
  inputs:
    SonarCloud: 'aspnetcoredemo'
    organization: 'umeshtangawade'
    scannerMode: 'MSBuild'
    projectKey: 'aspnetcoredemo'
    projectName: 'aspnetcoredemo'
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: '$(Parameters.RestoreBuildProjects)'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: '$(Parameters.TestProjects)'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
    zipAfterPublish: True
- task: SonarCloudAnalyze@1
  displayName: Sonar Cloud Analyze
- task: SonarCloudPublish@1
  displayName: Sonar Cloud Publish
  inputs:
    pollingTimeoutSec: '300'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()